/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "STM32_Registers.h"

//GPIOA pin 5 is connected to on board LED; using GPIOC for rows instead of GPIOA

unsigned char readKeypad(void);
int main(void)
{
	//Enable clock for GPIOA
	RCC_AHB1ENR->GPIOAEN = 1;

	RCC_AHB1ENR->GPIOCEN = 1;

	//Configure A0-A3 as inputs and A4-A7 as outputs
	/*GPIOA_MODER->MODER0 = 0;
	GPIOA_MODER->MODER1 = 0;
	GPIOA_MODER->MODER2 = 0;
	GPIOA_MODER->MODER3 = 0;*/
	GPIOA_MODER->MODER4 = 1;
	GPIOA_MODER->MODER5 = 1;
	GPIOA_MODER->MODER6 = 1;
	GPIOA_MODER->MODER7 = 1;

	GPIOC_MODER->MODER0 = 0;
	GPIOC_MODER->MODER1 = 0;
	GPIOC_MODER->MODER2 = 0;
	GPIOC_MODER->MODER3 = 0;

	/*//Pull down A0-A3:
	GPIOA_PUPDR->PUPDR0 = 2;
	GPIOA_PUPDR->PUPDR1 = 2;
	GPIOA_PUPDR->PUPDR2 = 2;
    GPIOA_PUPDR->PUPDR3 = 2;*/
	//Pull down PC0-3 (2 for PD)
	GPIOC_PUPDR->PUPDR0 = 2;
	GPIOC_PUPDR->PUPDR1 = 2;
	GPIOC_PUPDR->PUPDR2 = 2;
	GPIOC_PUPDR->PUPDR3 = 2;

    printf("Waiting for keypad input...\n");



	while (1){
		//fetch digit value returned by keypad and assign to key
		unsigned char key = readKeypad();
		if (key != 0xFF){
			//Print corresponding keys
			// (1/2) keep numerical value for <9
			// (2/2) For letters and */# use a special case
			if (key <= 9) {
				printf("Key Pressed: %d\n", key);
			} else if (key == 10) {
				printf("Key Pressed: A\n");
			} else if (key == 11) {
				printf("Key Pressed: B\n");
			} else if (key == 12) {
				printf("Key Pressed: C\n");
			} else if (key == 13) {
				printf("Key Pressed: D\n");
			} else if (key == 14) {
				printf("Key Pressed: *\n");
			} else if (key == 15) {
				printf("Key Pressed: #\n");
			}
		}
	}
}

unsigned char readKeypad(void) {
	unsigned char digit = 0xFF; // Default value if nothing is pressed
	unsigned char found = 0; // flag to detect key press
	while (!found){
		//Scan row 1 (PA4), turn PA4 on and PA5-7 off
		GPIOA_ODR->ODR4 = 1;
		GPIOA_ODR->ODR5 = 0;
		GPIOA_ODR->ODR6 = 0;
		GPIOA_ODR->ODR7 = 0;

		//delay and declare volatile so compiler doesn't delete
		//delay needed for long jumper wires used in this project
		for (volatile int delay = 0; delay < 100; delay++);


		//Since IDR struct looks 1 pin at a time bypass it by:
		//1. GPIOA base plus offset for IDR Register, resulting in 0x40020010
		//2. Typecast colatile uint32_t* to set as ptr
		//3. Dereference to fetch the string
		//4. &0x0F to fetch only 4 bits (PA0-PA3)

		//uint32_t columns = (*((volatile uint32_t*)(GPIOA_BASE + 0x10))) & 0x0F;

		//updated for GPIOC:
		uint32_t columns = (*((volatile uint32_t*)(GPIOC_BASE + 0x10))) & 0x0F;

		/* IDR (read) to read bits 0-3 of PortA (Pins 0-3)
		 */
		//Check if button was pressed:
		switch (columns) {
			case 1:  // Binary 0001 (PA0 / Col 1 is HIGH) -> Key '1'
				digit = 1;
		        found = 1;
		        break;
			case 2:  // Binary 0010 (PA1 / Col 2 is HIGH) -> Key '2'
				digit = 2;
				found = 1;
				break;
			case 4:  // Binary 0100 (PA2 / Col 3 is HIGH) -> Key '3'
				digit = 3;
				found = 1;
				break;
			case 8:  // Binary 1000 (PA3 / Col 4 is HIGH) -> Key 'A'
				digit = 10; // Usinf 10 to represent 'A'
				found = 1;
				break;
		}
		if (found == 1) break;


		//Continuously update columns to check next row

		//scan row 2 (PA5)
		GPIOA_ODR->ODR4 = 0;
		GPIOA_ODR->ODR5 = 1; // Row 2 ON
		GPIOA_ODR->ODR6 = 0;
		GPIOA_ODR->ODR7 = 0;

		for (volatile int delay = 0; delay < 100; delay++);
		//columns = (*((volatile uint32_t*)(GPIOA_BASE + 0x10))) & 0x0F;
		columns = (*((volatile uint32_t*)(GPIOC_BASE + 0x10))) & 0x0F;

		switch (columns) {
			case 1: digit = 4; found = 1; break; // Key '4'
			case 2: digit = 5; found = 1; break; // Key '5'
			case 4: digit = 6; found = 1; break; // Key '6'
			case 8: digit = 11; found = 1; break; // Key 'B'
		}
		if (found == 1) break;

		//Scan Row 3 (PA6):
		GPIOA_ODR->ODR4 = 0;
		GPIOA_ODR->ODR5 = 0;
		GPIOA_ODR->ODR6 = 1; // Row 3 ON
		GPIOA_ODR->ODR7 = 0;

		for (volatile int delay = 0; delay < 100; delay++);
		//columns = (*((volatile uint32_t*)(GPIOA_BASE + 0x10))) & 0x0F;
		columns = (*((volatile uint32_t*)(GPIOC_BASE + 0x10))) & 0x0F;

		switch (columns) {
			case 1: digit = 7; found = 1; break; // Key '7'
			case 2: digit = 8; found = 1; break; // Key '8'
			case 4: digit = 9; found = 1; break; // Key '9'
			case 8: digit = 12; found = 1; break; // Key 'C'
		}
		if (found == 1) break;

		//Scna Row 4 (PA7):
		GPIOA_ODR->ODR4 = 0;
		GPIOA_ODR->ODR5 = 0;
		GPIOA_ODR->ODR6 = 0;
		GPIOA_ODR->ODR7 = 1; // Row 4 ON

		for (volatile int delay = 0; delay < 100; delay++);
		//columns = (*((volatile uint32_t*)(GPIOA_BASE + 0x10))) & 0x0F;
		columns = (*((volatile uint32_t*)(GPIOC_BASE + 0x10))) & 0x0F;

		switch (columns) {
			case 1: digit = 14; found = 1; break; // Key '*' (Using 14)
			case 2: digit = 0; found = 1; break;  // Key '0'
			case 4: digit = 15; found = 1; break; // Key '#' (Using 15)
			case 8: digit = 13; found = 1; break; // Key 'D'
		}
		if (found == 1) break;
	}
	/*while ( (*((volatile uint32_t*)(GPIOA_BASE + 0x10)) & 0x0F) != 0 ) {
		//wait while button is being held
		//If a button is being held, PORTA 0-3 never reads 0 (IDR isn't 0)
	}*/
	while ( (*((volatile uint32_t*)(GPIOC_BASE + 0x10)) & 0x0F) != 0 ) {

	}
	//Also debounce delay:
	for (volatile int delay = 0; delay < 10000; delay++);

	return digit;
}
